name: Batch Image Labeling Pipeline

on:
  push:
    branches: main
  pull_request:
    branches: main


jobs:

  build-test-deploy:
    runs-on: self-hosted
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        lfs: true
      
    - name: List model file
      run: ls -lh inference/models/

    - name: Build Docker image
      run: docker compose build
    
    - name: Run unit tests
      run: docker compose run --rm fish-detector-tests

    - name: Start app for integration test
      run: docker compose up -d fish-detector
    
    - name: Run integration test
      run: curl http://localhost:8000/health

    - name: Deploy
      run: docker compose up -d fish-detector

